version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: credit_approval
      POSTGRES_USER: credituser
      POSTGRES_PASSWORD: creditpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: /start.sh
    volumes:
      - .:/app
      - ../data:/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A credit_approval worker -l info
    volumes:
      - .:/app
      - ../data:/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A credit_approval beat -l info
    volumes:
      - .:/app
      - ../data:/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
